import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./public/**/*.html"],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Cormorant Garamond"', "serif"],
        sans: ['"Inter"', "sans-serif"],
      },
      colors: {
        wedding: {
          page: "#faf8f4",
          surface: "#ffffff",
          onInk: "#ffffff",
          surfaceWarm: "#fcfaf7",
          panel: "#f4ede4",
          panelHover: "#faf3ed",
          panelSelected: "#f4ebe4",
          ink: "#2f2421",
          inkSoft: "#3b2f2b",
          heading: "#332824",
          muted: "#5f524c",
          mutedSoft: "#7a706a",
          mutedWarm: "#7c6f68",
          bodySoft: "#6c5c52",
          bodyMuted: "#6f625b",
          labelWarm: "#8b6f60",
          labelSoft: "#7b685e",
          value: "#4f433d",
          accent: "#9f7f6d",
          accentSoft: "#d9c1b1",
          accentWarm: "#b7937f",
          placeholder: "#a29185",
          border: "#e2d6ca",
          borderSoft: "#eadfd4",
          borderWarm: "#e6ddd2",
          borderPage: "#e8e0d8",
          chipBorder: "#d7c6b8",
          divider: "#dfd2c5",
          buttonHover: "#473632",
          successBg: "#f3fbf1",
          successBorder: "#c7d9c8",
          successText: "#38543a",
          successHeading: "#2f4a32",
          errorBg: "#fff7f5",
          errorPanel: "#fff4eb",
          errorBorder: "#c85745",
          errorRing: "#e7aaa0",
          errorPanelBorder: "#d8b197",
          errorText: "#c85745",
          errorPanelText: "#7b4c33",
        },
      },
      boxShadow: {
        "wedding-card": "0 24px 70px rgba(80,56,38,0.08)",
        "wedding-radio": "0 10px 28px rgba(80,56,38,0.10)",
        "wedding-dropdown": "0 18px 40px rgba(80,56,38,0.12)",
      },
    },
  },
} satisfies Config;
